version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PencaUCU  
      MYSQL_USER: bernardo
      MYSQL_PASSWORD: root
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql

